[package]
name = "local-search"
version = "0.1.0"
authors = ["Samuel Walladge"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tantivy = "0.10.1"
walkdir = "2.2.9"
structopt = "0.2.18"
