[main]
# Default index to use. Required if more than one index defined below.
default_index = "wiki"

# Multiple indexes can be supplied following the below format. Each index must
# have a unique name. Use a unique index_path per index.
[indexes.wiki]
# The directory to store the index files in. Must exist. Should be an absolute
# path.
index_path = "/home/swalladge/.wiki-index"
# List of files to index. Globbing supported - uses the glob crate - see
# https://docs.rs/glob/0.3.0/glob/ for behaviour specific to this globbing
# library.
files = [
  '/home/swalladge/wiki/**/*.md'
]
